version: '3.7'

services:

  multisig:
    container_name: multisig
    build:
      context: .
      dockerfile: .docker/node/Dockerfile
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - 3001:3000
    environment:
      - CHOKIDAR_USEPOLLING=true  
    stdin_open: true   

