version: '3.7'

services:
  multisig_dev:
    container_name: multisig_dev
    build:
      context: .
      dockerfile: .docker/node/Dockerfile
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - 3001:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
    stdin_open: true
